# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:12.18.2

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/test

    steps:
      - checkout
      - setup_remote_docker

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "./package.json" }}
            - v1-dependencies-{{ checksum "./express/package.json" }}
            - v1-dependencies-{{ checksum "./nuxt/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: cd ./express && yarn install

      - run: cd ./nuxt && yarn install

      - save_cache:
          paths:
            - ./node_modules
          key: v1-dependencies-{{ checksum "./package.json" }}

      - save_cache:
          paths:
            - ./express/node_modules
          key: v1-dependencies-{{ checksum "./express/package.json" }}

      - save_cache:
          paths:
            - ./express/node_modules
          key: v1-dependencies-{{ checksum "./nuxt/package.json" }}
 
      - run: yarn run lint

      - run: yarn run test

      - run: yarn run build
